### ISSUE TITLE
MSZ-25

### ISSUE THREAD

**Issue by skorc99** [Masurov/Domoticz-MitsubishiHpMQTT-Plugin#2]
Hello,

WEMOS D1
when using remote AC turns off.  

I added:
hp.enableAutoUpdate(); // <= this line should be added to prevent unsync if you use remote

Any idea?

U

**Comment by Euton2020** [comment]
hello, you have to put 2 lines:

hp.enableExternalUpdate ();
hp.enableAutoUpdate ();

and it works after
