### ISSUE TITLE
Devices merging between Gysmo38 plugin and this one

### ISSUE THREAD

**Issue by Patricen1** [Masurov/Domoticz-MitsubishiHpMQTT-Plugin#3]
Is there a way to use the created devices, especially setpoint that is different in between this plugin and Gysom38's plugin?
Gysmo38's plugin is using a multilevel switch for setpoint that is less convenient than a true setpoint as in this plugin.
I need to use the Melcloud plugin as I want to keep aircon connected to MELCloud.

Best,

Patricen

**Comment by Masurov** [comment]
Hi,

Sorry but you have to ask the setpoint device type modification in the Gysmo38's plugin issues. I can't do anything myself as I don't maintain its plugin.

Regards
